name: Validate

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    name: eslint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci # install dependencies

      - name: Run eslint
        run: npm run lint # run eslint
  prettier:
    runs-on: ubuntu-latest

    name: prettier
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci # install dependencies

      - name: Run prettier
        run: npm run prettier  # run prettier
